# these are lower bounds specified in TF's requirements.  Some are higher than
#    TF's lower bound.  These are higher because they are the lowest version that we have.
bazel:
  - 4.2.2
protobuf:
  - 3.20
libprotobuf:
  - 3.20
mkl:
  - 2021
