# these are lower bounds specified in TF's requirements.  Some are higher than
#    TF's lower bound.  These are higher because they are the lowest version that we have.
absl_py:
    - 0.7    # [py<38]
    - 0.8   # [py>37]
astunparse:
    - 1.6.3
bazel:
    - 3.1.0
gast:
    - 0.3.3  # [py<38]
    - 0.4.0  # [py>37]
google_pasta:
    - 0.1.8  # [py<38]
    - 0.2.0  # [py>37]
grpcio:
    - 1.16
h5py:
    - 2.10.0
keras_preprocessing:
    - 1.1.0
# tensorboard has this as a requirement
markdown:
    - 2.6.8  # [py<38]
    - 3.3.2  # [py>37]
numpy:
    - 1.16
opt_einsum:
    - 2.3.2  # [py<38]
    - 3.1.0  # [py>37]
protobuf:
    - 3.8.0  # [py<38]
    - 3.9.2  # [py>37]
# tensorboard has this as a requirement
setuptools:
    - 41.4   # [py<38]
    - 50.3   # [py>37]
# pinned to an exact version in the wheel, loosen for the conda package
scipy:
   - 1.4.1   # [py<38]
   - 1.5.2   # [py>37]
six:
    - 1.12  # [py<38]
    - 1.14  # [py>37]
termcolor:
    - 1.1.0
wrapt:
    - 1.11.2  # [py<38]
    - 1.12.1  # [py>37]
