{% set version = "1.13.1" %}

# This is the recipe for the "gpu" variant of tensorflow-base
package:
  name: tensorflow-base
  version: {{ version }}

source:
  fn: tensorflow-{{ version }}.tar.gz
  url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz
  sha256: 7cd19978e6bc7edc2c847bce19f95515a742b34ea5e28e4389dade35348f58ed
  patches:
    # Patches need to get certain tests to pass on CentOS 6
    - 0003-stable-image-rotate-test.patch                             # [linux]
    - 0004-relax-tolerence-in-special_math_test.patch                 # [linux]
    - 0005-skip-read-only-debugger_cli_common-test.patch              # [linux]
    - 0006-fix-lookup_ops-test.patch                                  # [linux]
    - 0007-relax-precision-in-matrix_log_op_test.patch                # [linux]
    # GPU patches
    - 0011-do-not-include-B-usr-bin-flag.patch                        # [linux]
    - 0012-add-additional-cuda-rpaths.patch                           # [linux]
    - 0013-Add-patch-for-eigen-cuda-19198.patch                       # [win]

build:
  number: 0
  string: gpu_py{{ CONDA_PY }}h{{PKG_HASH}}_{{ PKG_BUILDNUM }}
  skip: True  # [not x86_64]
  skip: True  # [win and vc<14]
  entry_points:
    - freeze_graph = tensorflow.python.tools.freeze_graph:run_main
    - toco_from_protos = tensorflow.lite.toco.python.toco_from_protos:main
    - tflite_convert = tensorflow.lite.python.tflite_convert:main
    - toco = tensorflow.lite.python.tflite_convert:main
    - saved_model_cli = tensorflow.python.tools.saved_model_cli:main
    - tf_upgrade_v2 = tensorflow.tools.compatibility.tf_upgrade_v2_main:main
    # The tensorboard package adds this entry point.
    # - tensorboard = tensorboard.main:run_main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel >=0.19.0,<=0.21.0
  host:
    # conda build requirements
    - posix  # [win]
    - m2-patch  # [win]
    - pip
    - setuptools <=39.1.0
    - python
    - swig
    - zlib
    # GPU requirements
    - cudatoolkit {{ cudatoolkit }}*
    - cudnn {{ cudnn }}*
    - cupti  # [not win]
    # requirements specified by the package itself
    - absl-py >=0.1.6
    - astor >=0.6.0
    - gast >=0.2.0
    - keras-applications >=1.0.5
    - keras-preprocessing >=1.0.3
    - numpy 1.13.3  # [py<37]
    # The requirement is numpy >=1.13 but no builds of numPy 1.13 are
    # available for Python 3.7
    - numpy 1.14.6  # [py==37]
    - six >=1.10.0
    - protobuf >=3.6.0
    - termcolor >=1.1.0
    - grpcio >=1.8.6
    - wheel >=0.26
    - mock >=2.0.0                # [py2k]
    - backports.weakref >=1.0rc1  # [py2k]
    - enum34 >=1.1.6              # [py2k]
    - tensorflow-estimator >=1.13.0,<1.14.0a0
    # the following packages are required for testing
    - m2-perl             # [win]
    - portpicker
    - pyreadline          # [win]
    - scipy
    - scikit-learn
  run:
    - python
    - absl-py >=0.1.6
    - astor >=0.6.0
    - gast >=0.2.0
    - keras-applications >=1.0.5
    - keras-preprocessing >=1.0.3
    - {{ pin_compatible('numpy') }}
    - six >=1.10.0
    - protobuf >=3.6.0
    - termcolor >=1.1.0
    - grpcio >=1.8.6
    - mock >=2.0.0                # [py2k]
    - backports.weakref >=1.0rc1  # [py2k]
    - enum34 >=1.1.6              # [py2k]
    - tensorflow-estimator >=1.13.0,<1.14.0a0
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
    - {{ pin_compatible('cudnn') }}
    - cupti  # [not win]

test:
  # the tensorflow import is tested by the run_test.sh script.
  # See comments in that file for the LD_LIBRARY_PATH requirements
  #imports:
  #  - tensorflow
  files:
    - gpu_test.py
  commands:
    - freeze_graph --help
    - saved_model_cli --help
    - tflite_convert --help     # [not win]
    - toco_from_protos --help   # [not win]
    - toco --help               # [not win]


about:
  home: http://tensorflow.org/
  license: Apache 2.0
  license_family: Apache
  summary: TensorFlow is a machine learning library, base GPU package, tensorflow only.
  description: |
    TensorFlow provides multiple APIs.The lowest level API, TensorFlow Core
    provides you with complete programming control.
    Base GPU package contains only tensorflow, not tensorflow-tensorboard.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src

extra:
  tflow_variant: {{ tflow_variant }}
