{% set version = "2.0.0" %}

package:
  name: tensorflow-estimator
  version: {{ version }}

source:
  fn: tensorflow-estimator-{{ version }}.tar.gz
  url: https://github.com/tensorflow/estimator/archive/v{{ version }}.tar.gz
  sha256: 6f4bdf1ab219e1f1cba25d2af097dc820f56479f12a839853d97422fe4d8b465

build:
  number: 0
  noarch: python

requirements:
  host:
    - bazel
    - python
    - tensorflow-base >=2.0.0,<2.1.0a0
    - pip
  run:
    - python
    - tensorflow-base >=2.0.0,<2.1.0a0

test:
  imports:
    - tensorflow_estimator

about:
  home: https://www.tensorflow.org/guide/estimators
  license: Apache 2.0
  license_family: Apache
  summary: TensorFlow Estimator
  description: |
    TensorFlow Estimator is a high-level API that encapsulates model
    training, evaluation, prediction, and exporting.
  dev_url: https://github.com/tensorflow/estimator
