{% set name = "tensorflow-estimator" %}
{% set version = "2.9.0" %}
{% set major_minor = version.rsplit('.', 1)[0] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/py2.py3/t/tensorflow-estimator/tensorflow_estimator-{{ version }}-py2.py3-none-any.whl
  sha256: e9762bb302f51bc1eb2f35d19f0190a6a2d809d754d5def788c4328fe3746744

build:
  number: 0
  skip: True  # [py<37]
  script:
    - python -m pip install --no-deps --ignore-installed tensorflow_estimator-{{ version }}-py2.py3-none-any.whl

requirements:
  host:
    - python
    - pip
  run:
    - python
  run_constrained:
    - tensorflow-base  {{ major_minor }}.*

about:
  home: https://www.tensorflow.org/guide/estimator
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: TensorFlow Estimator is a high-level TensorFlow API that greatly simplifies machine learning programming.
  dev_url: https://github.com/tensorflow/estimator
  doc_url: https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator

extra:
  recipe-maintainers:
    - sdvillal
    - gilbertfrancois
    - farhantejani
    - kyleabeauchamp
    - waitingkuo
    - ghego
    - hajapy
    - dhirschfeld
    - jschueller
