{% set version = "1.14.0" %}

package:
  name: tensorflow-estimator
  version: {{ version }}

source:
  fn: tensorflow-estimator-{{ version }}.tar.gz
  url: https://github.com/tensorflow/estimator/archive/v{{ version }}.tar.gz
  sha256: 1f0b80b8067a52cc33bbe390d34791eb3e12453c506daa1b4c8fc07fbf962d9f

build:
  number: 0
  noarch: python

requirements:
  host:
    - bazel
    - python
    - tensorflow-base 1.14.0
    - pip
  run:
    - python
    - absl-py >=0.1.6
    - numpy >=1.13.3
    - six >=1.10.0
    - mock >=2.0.0

test:
  requires:
    - tensorflow-base >=1.14.0,<1.15.0a0
  imports:
    - tensorflow_estimator

about:
  home: https://www.tensorflow.org/guide/estimators
  license: Apache 2.0
  license_family: Apache
  summary: TensorFlow Estimator
  description: |
    TensorFlow Estimator is a high-level API that encapsulates model
    training, evaluation, prediction, and exporting.
  dev_url: https://github.com/tensorflow/estimator
