{% set version = "2.3.0" %}
{% set tarball_version = "2.3.0" %}

package:
  name: tensorflow-estimator
  version: {{ version }}

source:
  fn: tensorflow-estimator-{{ version }}.tar.gz
  url: https://github.com/tensorflow/estimator/archive/v{{ tarball_version }}.tar.gz
  sha256: 75403e7de7e8ec30ec0781ede56ed84cbe5e90daad64a9c242cd489c8fe63a17

build:
  number: 0
  noarch: python

requirements:
  build:
    - bazel
  host:
    - pip
    - python
    - tensorflow-base {{ version }}
  run:
    - python >=3
    - {{ pin_compatible('tensorflow-base', max_pin='x.x') }}

test:
  imports:
    - tensorflow_estimator

about:
  home: https://www.tensorflow.org/guide/estimators
  license: Apache 2.0
  license_family: Apache
  summary: TensorFlow Estimator
  description: |
    TensorFlow Estimator is a high-level API that encapsulates model
    training, evaluation, prediction, and exporting.
  dev_url: https://github.com/tensorflow/estimator
