# configuration for win-64 gpu, cuda 9.0
full_base_version:
  - "1.13.1 gpu_py36h871c8ca_0"
  - "1.13.1 gpu_py37h871c8ca_0"
select_version:
  - "2.1.0 gpu"
  - "2.1.0 gpu"
tflow_variant:
  - "gpu"
  - "gpu"
py_version:
  - 3.6
  - 3.7
zip_keys:
  - full_base_version
  - select_version
  - tflow_variant
  - py_version
