full_base_version:
  - "2.1.0 eigen_py37h49b2757_0"
  - "2.1.0 eigen_py38h49b2757_0"
  - "2.1.0 eigen_py39haaaaaaa_0"
  - "2.1.0 mkl_py37h230818c_0"
  - "2.1.0 mkl_py38h230818c_0"
  - "2.1.0 mkl_py39hccccccc_0"
select_version:
  - "2.2.0 eigen"
  - "2.2.0 eigen"
  - "2.2.0 eigen"
  - "2.3.0 mkl"
  - "2.3.0 mkl"
  - "2.3.0 mkl"
tflow_variant:
  - "eigen"
  - "eigen"
  - "eigen"
  - "mkl"
  - "mkl"
  - "mkl"
py_version:
  - 3.7
  - 3.8
  - 3.9
  - 3.7
  - 3.8
  - 3.9
zip_keys:
  - full_base_version
  - select_version
  - tflow_variant
  - py_version
