# configuration for linux-64 gpu, cuda 10.1
full_base_version:
  - "1.15.0 gpu_py27he45bfe2_0"
  - "1.15.0 gpu_py36he45bfe2_0"
  - "1.15.0 gpu_py37he45bfe2_0"
select_version:
  - "2.1.0 gpu"
  - "2.1.0 gpu"
  - "2.1.0 gpu"
tflow_variant:
  - "gpu"
  - "gpu"
  - "gpu"
py_version:
  - 2.7
  - 3.6
  - 3.7
zip_keys:
  - full_base_version
  - select_version
  - tflow_variant
  - py_version
