# configuration for linux-64 gpu, cuda 10.1
full_base_version:
  - "2.2.0 gpu_py36h8a81be8_0"
  - "2.2.0 gpu_py37h8a81be8_0"
  - "2.2.0 gpu_py38h8a81be8_0"
select_version:
  - "2.1.0 gpu"
  - "2.1.0 gpu"
  - "2.1.0 gpu"
tflow_variant:
  - "gpu"
  - "gpu"
  - "gpu"
py_version:
  - 3.6
  - 3.7
  - 3.8
zip_keys:
  - full_base_version
  - select_version
  - tflow_variant
  - py_version
