# configuration for linux-64 eigen and mkl variants
full_base_version:
  - "1.11.0 eigen_py27h4dcebc2_0"
  - "1.11.0 eigen_py36h4dcebc2_0"
  - "1.11.0 mkl_py27h3c3e929_0"
  - "1.11.0 mkl_py36h3c3e929_0"
select_version:
  - "2.2.0 eigen"
  - "2.2.0 eigen"
  - "2.3.0 mkl"
  - "2.3.0 mkl"
tflow_variant:
  - "eigen"
  - "eigen"
  - "mkl"
  - "mkl"
py_version:
  - 2.7
  - 3.6
  - 2.7
  - 3.6
zip_keys:
  - full_base_version
  - select_version
  - tflow_variant
  - py_version
