# configuration for linux-64 eigen and mkl variants
full_base_version:
  - "2.3.0 eigen_py37h3b305d7_0"
  - "2.3.0 eigen_py38hb57a387_0"
  - "2.3.0 mkl_py37he9661a2_0"
  - "2.3.0 mkl_py38hac35e67_0"
select_version:
  - "2.3.0 eigen"
  - "2.3.0 eigen"
  - "2.3.0 mkl"
  - "2.3.0 mkl"
tflow_variant:
  - "eigen"
  - "eigen"
  - "mkl"
  - "mkl"
py_version:
  - 3.7
  - 3.8
  - 3.7
  - 3.8
zip_keys:
  - full_base_version
  - select_version
  - tflow_variant
  - py_version
