# configuration for linux-64 eigen and mkl variants
full_base_version:
  - "2.8.2 eigen_py37h980454f_0"
  - "2.8.2 eigen_py38h980454f_0"
  - "2.8.2 eigen_py39h980454f_0"
  - "2.8.2 eigen_py310h980454f_0"
  - "2.8.2 mkl_py37hf890080_0"
  - "2.8.2 mkl_py38hf890080_0"
  - "2.8.2 mkl_py39hf890080_0"
  - "2.8.2 mkl_py310hf890080_0"

select_version:
  - "2.2.0 eigen"
  - "2.2.0 eigen"
  - "2.2.0 eigen"
  - "2.2.0 eigen"
  - "2.3.0 mkl"
  - "2.3.0 mkl"
  - "2.3.0 mkl"
  - "2.3.0 mkl"

tflow_variant:
  - "eigen"
  - "eigen"
  - "eigen"
  - "eigen"
  - "mkl"
  - "mkl"
  - "mkl"
  - "mkl"

py_version:
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  - 3.7
  - 3.8
  - 3.9
  - 3.10

zip_keys:
  - full_base_version
  - select_version
  - tflow_variant
  - py_version
