# configuration for linux-64 eigen and mkl variants
full_base_version:
  - "2.10.0 eigen_py37h1969d1f_0"
  - "2.10.0 eigen_py38h1969d1f_0"
  - "2.10.0 eigen_py39h1969d1f_0"
  - "2.10.0 eigen_py310h1969d1f_0"
  - "2.10.0 mkl_py37hb9daa73_0"
  - "2.10.0 mkl_py38hb9daa73_0"
  - "2.10.0 mkl_py39hb9daa73_0"
  - "2.10.0 mkl_py310hb9daa73_0"

select_version:
  - "2.2.0 eigen"
  - "2.2.0 eigen"
  - "2.2.0 eigen"
  - "2.2.0 eigen"
  - "2.3.0 mkl"
  - "2.3.0 mkl"
  - "2.3.0 mkl"
  - "2.3.0 mkl"

tflow_variant:
  - "eigen"
  - "eigen"
  - "eigen"
  - "eigen"
  - "mkl"
  - "mkl"
  - "mkl"
  - "mkl"

py_version:
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  - 3.7
  - 3.8
  - 3.9
  - 3.10

zip_keys:
  - full_base_version
  - select_version
  - tflow_variant
  - py_version
