full_base_version:
  - "2.0.0 eigen_py36h01553b8_0"
  - "2.0.0 eigen_py37h01553b8_0"
  - "2.0.0 mkl_py36hd1d5974_0"
  - "2.0.0 mkl_py37hd1d5974_0"
select_version:
  - "2.2.0 eigen"
  - "2.2.0 eigen"
  - "2.3.0 mkl"
  - "2.3.0 mkl"
tflow_variant:
  - "eigen"
  - "eigen"
  - "mkl"
  - "mkl"
py_version:
  - 3.6
  - 3.7
  - 3.6
  - 3.7
zip_keys:
  - full_base_version
  - select_version
  - tflow_variant
  - py_version
