# configuration for linux-64 gpu, cuda 9.0
full_base_version:
  - "1.11.0 gpu_py27h8e0ae2d_0"
  - "1.11.0 gpu_py36h8e0ae2d_0"
select_version:
  - "2.1.0 gpu"
  - "2.1.0 gpu"
tflow_variant:
  - "gpu"
  - "gpu"
py_version:
  - 2.7
  - 3.6
zip_keys:
  - full_base_version
  - select_version
  - tflow_variant
  - py_version
