# configuration for linux-64 gpu, cuda 9.2
full_base_version:
  - "1.14.0 gpu_py27h611c6d2_0"
  - "1.14.0 gpu_py36h611c6d2_0"
  - "1.14.0 gpu_py37h611c6d2_0"
select_version:
  - "2.1.0 gpu"
  - "2.1.0 gpu"
  - "2.1.0 gpu"
tflow_variant:
  - "gpu"
  - "gpu"
  - "gpu"
py_version:
  - 2.7
  - 3.6
  - 3.7
zip_keys:
  - full_base_version
  - select_version
  - tflow_variant
  - py_version
