# configuration for linux-64 gpu, cuda 10.1
full_base_version:
  - "2.4.1 gpu_py37h29c2da4_0"
  - "2.4.1 gpu_py38h29c2da4_0"
  - "2.4.1 gpu_py39h29c2da4_0"
select_version:
  - "2.1.0 gpu"
  - "2.1.0 gpu"
  - "2.1.0 gpu"
tflow_variant:
  - "gpu"
  - "gpu"
  - "gpu"
py_version:
  - 3.7
  - 3.8
  - 3.9
zip_keys:
  - full_base_version
  - select_version
  - tflow_variant
  - py_version
