# Configuration for osx-arm64 eigen variant.
# Note that we don't build for Python 3.7 due to numpy limitations.
full_base_version:
  - "2.11.0 eigen_py38h8747ca9_0"
  - "2.11.0 eigen_py39h8747ca9_0"
  - "2.11.0 eigen_py310h8747ca9_0"

select_version:
  - "2.2.0 eigen"
  - "2.2.0 eigen"
  - "2.2.0 eigen"

tflow_variant:
  - "eigen"
  - "eigen"
  - "eigen"

py_version:
  - 3.8
  - 3.9
  - 3.10

zip_keys:
  - full_base_version
  - select_version
  - tflow_variant
  - py_version
