# configuration for linux-64 eigen and mkl variants
full_base_version:
  - "1.15.0 eigen_py27hd4672e3_0"
  - "1.15.0 eigen_py36h52b156a_0"
  - "1.15.0 eigen_py37h52b156a_0"
  - "1.15.0 mkl_py27h503033c_0"
  - "1.15.0 mkl_py36he1670d9_0"
  - "1.15.0 mkl_py37he1670d9_0"
select_version:
  - "2.2.0 eigen"
  - "2.2.0 eigen"
  - "2.2.0 eigen"
  - "2.3.0 mkl"
  - "2.3.0 mkl"
  - "2.3.0 mkl"
tflow_variant:
  - "eigen"
  - "eigen"
  - "eigen"
  - "mkl"
  - "mkl"
  - "mkl"
py_version:
  - 2.7
  - 3.6
  - 3.7
  - 2.7
  - 3.6
  - 3.7
zip_keys:
  - full_base_version
  - select_version
  - tflow_variant
  - py_version
