# configuration for linux-64 eigen and mkl variants
full_base_version:
  - "2.11.0 eigen_py38h3323580_0"
  - "2.11.0 eigen_py39h3323580_0"
  - "2.11.0 eigen_py310h3323580_0"
  - "2.11.0 mkl_py38he5f8e37_0"
  - "2.11.0 mkl_py39he5f8e37_0"
  - "2.11.0 mkl_py310he5f8e37_0"

select_version:
  - "2.2.0 eigen"
  - "2.2.0 eigen"
  - "2.2.0 eigen"
  - "2.3.0 mkl"
  - "2.3.0 mkl"
  - "2.3.0 mkl"

tflow_variant:
  - "eigen"
  - "eigen"
  - "eigen"
  - "mkl"
  - "mkl"
  - "mkl"

py_version:
  - 3.8
  - 3.9
  - 3.10
  - 3.8
  - 3.9
  - 3.10

zip_keys:
  - full_base_version
  - select_version
  - tflow_variant
  - py_version
