{% set version = "1.9.0" %}

package:
  name: tensorflow
  version: {{ version }}

build:
  number: 0
  skip: True  # [not x86_64]
  string: {{ tflow_variant }}_py{{ CONDA_PY }}h{{PKG_HASH}}_{{ PKG_BUILDNUM }}  # [linux]

requirements:
  run:
    - tensorflow-base =={{version}}               # [win]
    - python {{ py_version }}                     # [linux]
    - tensorflow-base =={{ full_base_version }}   # [linux]
    - _tflow_190_select =={{ select_version }}    # [linux]
    - tensorboard >=1.9.0,<1.10.0

test:
  imports:
    - tensorflow
    - tensorboard
  commands:
    # has an exit code of 1, see tensorboard recipe
    - tensorboard --help || true  # [unix]

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  license_family: Apache
  summary: TensorFlow is a machine learning library.
  description: |
    TensorFlow provides multiple APIs.The lowest level API, TensorFlow Core
    provides you with complete programming control.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src
