# Builds fail on linux with gcc 7.x, see
# https://github.com/tensorflow/tensorflow/issues/25323
c_compiler_version:    # [linux and not aarch64]
  - 5.4                # [linux and not aarch64]
cxx_compiler_version:  # [linux and not aarch64]
  - 5.4                # [linux and not aarch64]
cxx_compiler:  # [win]
  - vs2019     # [win]
c_compiler:    # [win]
  - vs2019     # [win]
tflow_variant:
#  - mkl
#  - eigen
  - onednn

# ACL versions can be found here:
# https://review.mlplatform.org/admin/repos/ml/ComputeLibrary,branches
acl_version:                       # [aarch64]
  - branches/arm_compute_21_05     # [aarch64]

# OneDNN versions can be found here:
# https://github.com/oneapi-src/oneDNN/tags
onednn_version:                    # [aarch64]
  - v2.2.4                         # [aarch64]
onednn_build:                      # [aarch64]
  - acl                            # [aarch64]

