c_compiler_version:    # [linux and not aarch64]
  - 7.5                # [linux and not aarch64]
cxx_compiler_version:  # [linux and not aarch64]
  - 7.5                # [linux and not aarch64]
cxx_compiler:  # [win]
  - vs2019     # [win]
c_compiler:    # [win]
  - vs2019     # [win]
tflow_variant:
  #  - mkl
  - eigen
bazel:
  - 4.2.2
protobuf:
  - 3.20
libprotobuf:
  - 3.20
mkl:
  - 2021
