{% set version = "2.8.2" %}

# This is the recipe for the "mkl" and "eigen" variants of tensorflow-base
package:
  name: tensorflow-base
  version: {{ version }}

source:
  fn: tensorflow-{{ version }}.tar.gz
  url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz
  sha256: b3f860c02c22a30e9787e2548ca252ab289a76b7778af6e9fa763d4aafd904c7
  patches:
    - tensorflow_win_zip64.patch                            # [win]
    - 0101-include-c-and-cc-headers.patch                   # [unix]
    - 0103-BUILD-changes-for-external-sqlite-package.patch  # [linux]
    - 0107-do-not-hardcode-ca-cert-location.patch           # [unix]

build:
  number: 0
  skip: True  # [not x86_64 and not (linux and aarch64)]
  skip: True  # [win and vc<14]
  string: {{ tflow_variant }}_py{{ CONDA_PY }}h{{PKG_HASH}}_{{ PKG_BUILDNUM }}
  entry_points:
    - toco_from_protos = tensorflow.lite.toco.python.toco_from_protos:main
    - tflite_convert = tensorflow.lite.python.tflite_convert:main
    - toco = tensorflow.lite.python.tflite_convert:main
    - saved_model_cli = tensorflow.python.tools.saved_model_cli:main
    # The tensorboard package adds this entry point.
    # - tensorboard = tensorboard.main:run_main
    - tf_upgrade_v2 = tensorflow.tools.compatibility.tf_upgrade_v2_main:main
    - estimator_ckpt_converter = tensorflow_estimator.python.estimator.tools.checkpoint_converter:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
    - patch       # [unix]
    - m2-patch    # [win]
    # required here for all OS's, and ALSO below for windows
    - bazel >=4.2.2,<5
    - aws-sdk-cpp
    - cython
    - sqlite
    - grpc-cpp
    - wheel
  host:
    # conda build requirements for .sh scripts on win
    - posix     # [win]
    - m2-patch  # [win]
    - bazel >=4.2.2,<5    # [win]
    - python
    - pip
    - setuptools
    - wheel
    - libcurl
    - curl        # [win]
    - unzip        # [not win]
    - zip          # [not win]
    - m2-unzip     # [win]
    - m2-zip       # [win]
    - m2-perl      # [win]
    - nsync
    # requirements specified by the package itself
    - astor >=0.7.1
    - cython
    - dill >=0.3.1.1
    - giflib
    - grpc-cpp
    - flatbuffers 1.12.0
    - icu
    - jpeg
    - libpng
    - libprotobuf
    - openssl
    - pybind11
    - sqlite
    - snappy
    - zlib
    - abseil-cpp
    - absl-py 0.10  # [py<39]
    - absl-py 0.11  # [py>=39]
    - astunparse 1.6.3
    - python-flatbuffers 1.12.*
    - gast 0.4.0
    - google-pasta 0.2
    - grpcio
    - h5py >=3.1.0
    - keras-preprocessing >=1.1.2
    # has run_exports, doesn't need a run dep below
    # - mklml            # [win and tflow_variant == 'mkl']
    - numpy >=1.20  # [not aarch64]
    - numpy >=1.19  # [aarch64]
    - opt_einsum 3.3.0.*
    # build only requirement, doesn't need a run dep below
    - protobuf
    # build only requirement, doesn't need a run dep below
    - scipy
    - six >=1.15.0
    - typing_extensions >=3.7.4
    # build only requirement, doesn't need a run dep below
    - swig
    - termcolor >=1.1.0
    - wrapt >=1.11.2
    # has run_exports, doesn't need a run dep below
    - sqlite
    - snappy
    - typing_extensions >=3.7.4
    - tensorboard >=2.8,<2.9
    - tensorflow-estimator >=2.8,<2.9
  run:
    - python
    - absl-py >=0.10.0
    - astunparse >=1.6.3
    - python-flatbuffers 1.12.*
    - google-pasta >=0.2
    - h5py >=3.1.0
    - keras-preprocessing >=1.1.2
    - numpy >=1.20  # [not aarch64]
    - numpy >=1.19  # [aarch64]
    - opt_einsum 3.3.0.*
    - six >=1.15.0
    - termcolor >=1.1.0
    - typing_extensions >=3.7.4
    - wheel >=0.35,<0.36
    - wrapt >=1.11.2
    - grpcio
    # upstream wants exact pin for gast
    - gast ==0.4.0
    - {{ pin_compatible('scipy', max_pin=None) }}
    - flatbuffers
    - tensorboard >=2.8,<2.9
    - tensorflow-estimator >=2.8,<2.9
test:
  imports:
    - tensorflow
  commands:
    # estimator_ckpt_converter requires tensorflow-estimator
    #- estimator_ckpt_converter --help
    - saved_model_cli --help
    - tf_upgrade_v2 --help
    {% if unix -%}
    - tflite_convert --help
    - toco --help
    - toco_from_protos --help
    {%- endif %}

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  license_family: Apache
  summary: TensorFlow is a machine learning library, base package contains only tensorflow.
  description: |
    TensorFlow provides multiple APIs.The lowest level API, TensorFlow Core
    provides you with complete programming control.
    Base package contains only tensorflow, not tensorflow-tensorboard.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src

extra:
  tflow_variant: {{ tflow_variant }}
