{% set name = "tensorboard-plugin-wit" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/t/tensorboard/tensorboard-{{ version }}-py3-none-any.whl
  url: https://pypi.io/packages/py3/t/tensorboard-plugin-wit/tensorboard_plugin_wit-{{ version }}-py3-none-any.whl
  sha256: ff26bdd583d155aa951ee3b152b3d0cffae8005dc697f72b44a8e8c2a77a8cbe

build:
  number: 0
  skip: True  # [py<37]
  script:
    - python -m pip install --no-deps --ignore-installed ./tensorboard_plugin_wit-{{ version }}-py3-none-any.whl

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - wheel >=0.26
    # setuptools is required for pkg_resources
    - setuptools

test:
  imports:
    - tensorboard_plugin_wit

about:
  home: https://pair-code.github.io/what-if-tool/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: What-If Tool TensorBoard plugin
  dev_url: https://github.com/PAIR-code/what-if-tool
  doc_url: https://pair-code.github.io/what-if-tool/learn/
