{% set version = "1.6.0" %}

package:
  name: tensorboard-plugin-wit
  version: {{ version }}

source:
  #fn: tensorboard-plugin-wit-{{ version }}.tar.gz
  #url: https://github.com/PAIR-code/what-if-tool/archive/v{{ version }}.tar.gz
  #sha256: 1098777db63d2ce8b365bc7f21722066d0b0aff63bfc2cd8b1a6abfac5b9f760
  # The 1.6.0.post3 wheels looks to be build after
  # https://github.com/PAIR-code/what-if-tool/pull/64 was merged
  git_url: https://github.com/PAIR-code/what-if-tool.git
  git_hash: 01fcc6aa68cc26e5b234270550944262047aa263

# tensorboard-plugin-wit is built as a noarch packages on a Linux system
# During the build, an executable is downloaded that requires a newer
# version of libstdc++ than that provided by CentOS 6,  Ubuntu 16.04 works.
build:
  number: 0
  noarch: python
  string: py_{{ PKG_BUILDNUM }}
  # Although compilers are needed for the build, the output is pure python,
  # javascript and html. Therefore the run_exports can be ignored.
  ignore_run_exports:
    - libgcc-ng
    - libstdcxx-ng

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel
  host:
    - pip
    - python
  run:
    - python >=3
    # setuptools is required for pkg_resources
    - setuptools

test:
  imports:
    - tensorboard_plugin_wit

about:
  home: https://github.com/PAIR-code/what-if-tool 
  license: Apache 2.0
  license_family: Apache
  summary: What-If Tool TensorBoard plugin
