{% set version = "1.11.0" %}

# This is the recipe for the "mkl" and "eigen" variants of tensorflow-base
package:
  name: tensorflow-base
  version: {{ version }}

source:
  fn: tensorflow-{{ version }}.tar.gz
  url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz
  sha256: f49ce3f1d04cee854bc9f74fa9696991140b34a2e2447f35f01391b72c8bfa9f
  patches:
    - 0001-add-rt-to-linkopts.patch                             # [linux]
    - 0002-patch-third-party-libs-to-support-glibc-2.11.patch   # [linux]
    - 0004-Escape-regex-pattern-properly-before-using-it.patch
    # Patches need to get certain tests to pass on CentOS 6
    - 0005-stable-image-rotate-test.patch                       # [linux]
    - 0006-relax-tolerence-in-special_math_test.patch           # [linux]
    - 0007-skip-read-only-debugger_cli_common-test.patch        # [linux]
    - 0008-fix-lookup_ops-test.patch                            # [linux]
    - 0009-relax-precision-in-matrix_log_op_test.patch          # [linux]
    # set OpenMP variables for MKL variant
    - 0010-set-default-openmp-variables.patch   # [tflow_variant == 'mkl']
    - 0011-Add-init-symbol-names-prefixed-with-an-underscore.patch  # [osx]
    - 0012-Add-alternate-clock_gettime-implementation-for-macOS.patch  # [osx]

build:
  number: 0
  skip: True  # [not x86_64]
  skip: True  # [win and vc<14]
  string: {{ tflow_variant }}_py{{ CONDA_PY }}h{{PKG_HASH}}_{{ PKG_BUILDNUM }}
  entry_points:
    - freeze_graph = tensorflow.python.tools.freeze_graph:run_main
    - saved_model_cli = tensorflow.python.tools.saved_model_cli:main
    - tflite_convert = tensorflow.contrib.lite.python.tflite_convert:main
    - toco = tensorflow.contrib.lite.python.tflite_convert:main
    - toco_from_protos = tensorflow.contrib.lite.toco.python.toco_from_protos:main
    # The tensorboard package adds this entry point.
    # - tensorboard = tensorboard.main:run_main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # conda build requirements
    - bazel >=0.10.0
    - posix  # [win]
    - m2-patch  # [win]
    - pip
    - setuptools <=39.1.0
    - python
    - swig
    - zlib
    # requirements specified by the package itself
    - wheel >=0.26
    - termcolor >=1.1.0
    - six >=1.10.0
    - protobuf >=3.6.0
    - numpy 1.13.3
    - mock >=2.0.0        # [py2k]
    - grpcio >=1.8.6
    - gast >=0.2.0
    - enum34 >=1.1.6      # [py2k]
    - backports.weakref >=1.0rc1  # [py2k]
    - astor >=0.6.0
    - absl-py >=0.1.6
    - keras-applications >=1.0.5
    - keras-preprocessing >=1.0.3
    # the following packages are required for testing
    - m2-perl             # [win]
    - portpicker
    - pyreadline          # [win]
    - scipy
    - scikit-learn
    - mklml            # [win and tflow_variant == 'mkl']
  run:
    - python
    - termcolor >=1.1.0
    - six >=1.10.0
    - protobuf >=3.6.0
    - {{ pin_compatible('numpy') }}
    - mock >=2.0.0        # [py2k]
    - grpcio >=1.8.6
    - gast >=0.2.0
    - enum34 >=1.1.6      # [py2k]
    - backports.weakref >=1.0rc1  # [py2k]
    - astor >=0.6.0
    - absl-py >=0.1.6
    - keras-applications >=1.0.5
    - keras-preprocessing >=1.0.3

test:
  imports:
    - tensorflow
  commands:
    - freeze_graph --help
    - saved_model_cli --help
    - tflite_convert --help         # [not win]
    - toco_from_protos --help       # [not win]
    - toco --help                   # [not win]
    - conda inspect linkages -p $PREFIX tensorflow-base  # [linux]

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  license_family: Apache
  summary: TensorFlow is a machine learning library, base package contains only tensorflow.
  description: |
    TensorFlow provides multiple APIs.The lowest level API, TensorFlow Core
    provides you with complete programming control.
    Base package contains only tensorflow, not tensorflow-tensorboard.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src

extra:
  tflow_variant: {{ tflow_variant }}
