{% set version = "2.0.0" %}

# This is the recipe for the "mkl" and "eigen" variants of tensorflow-base
package:
  name: tensorflow-base
  version: {{ version }}

source:
  fn: tensorflow-{{ version }}.tar.gz
  url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz
  sha256: 49b5f0495cd681cbcb5296a4476853d4aea19a43bdd9f179c928a977308a0617
  patches:
    # - 0001-add-rt-to-linkopts.patch                                     # [linux]
    # - 0002-stable-image-rotate-test.patch                               # [linux]
    # - 0003-relax-tolerence-in-special_math_test.patch                   # [linux]
    # - 0004-skip-read-only-debugger_cli_common-test.patch                # [linux]
    # - 0005-fix-lookup_ops-test.patch                                    # [linux]
    # - 0006-relax-precision-in-matrix_log_op_test.patch                  # [linux]
    #- 0007-Add-init-symbol-names-prefixed-with-an-underscore.patch      # [osx] # merged upstream
    # https://github.com/tensorflow/tensorflow/issues/31520#issuecomment-524584978
    - 0001-rebatch-constants.patch
    - 0008-Add-alternate-clock_gettime-implementation-for-macOS.patch   # [osx]
    - 0012-set-default-kmp-variables.patch                              # [tflow_variant == 'mkl']
    - 0001-disable-prompt-for-ios-support.patch                         # [osx]

build:
  number: 0
  skip: True  # [not x86_64]
  skip: True  # [win and vc<14]
  string: {{ tflow_variant }}_py{{ CONDA_PY }}h{{PKG_HASH}}_{{ PKG_BUILDNUM }}
  entry_points:
    - toco_from_protos = tensorflow.lite.toco.python.toco_from_protos:main
    - tflite_convert = tensorflow.lite.python.tflite_convert:main
    - toco = tensorflow.lite.python.tflite_convert:main
    - saved_model_cli = tensorflow.python.tools.saved_model_cli:main
    # The tensorboard package adds this entry point.
    # - tensorboard = tensorboard.main:run_main
    - tf_upgrade_v2 = tensorflow.tools.compatibility.tf_upgrade_v2_main:main
    - estimator_ckpt_converter = tensorflow_estimator.python.estimator.tools.checkpoint_converter:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel >=0.24.1,<0.26.1a0
  host:
    - bazel >=0.24.1,<0.26.1a0  # [win]
    # conda build requirements
    - posix  # [win]
    - m2-patch  # [win]
    - pip >=19
    - setuptools <=39.1.0
    - python
    - numpy 1.16
    - pip
    - swig
    - zlib
    # requirements specified by the package itself
    - absl-py 0.7
    - astor 0.6.2
    - gast 0.2.2
    - google-pasta 0.1.7
    - keras-applications 1.0.8
    - keras-preprocessing 1.0.5
    - numpy-devel 1.16
    - six 1.12.0
    - protobuf 3.6.1
    - termcolor 1.1.0
    # actual bound is 1.8, but 1.14 is the current baseline covered by builds on defaults
    - grpcio 1.14
    - wheel >=0.26
    - mock 2.0.0                # [py2k]
    - backports.weakref         # [py2k]
    - future                    # [py2k]
    - enum34 1.1.6              # [py2k]
    # the following packages are required for testing
    - m2-perl             # [win]
    - portpicker
    - pyreadline          # [win]
    - scipy
    - scikit-learn
    - mklml            # [win and tflow_variant == 'mkl']
  run:
    - python
    # pin_compatible here is just to be lazy and define the dep versions in only one place.  These
    #    don't have binary compatibility issues.
    - {{ pin_compatible('absl-py') }}
    - {{ pin_compatible('astor') }}
    - {{ pin_compatible('gast', max_pin='x.x.x') }}
    - {{ pin_compatible('keras-applications') }}
    - {{ pin_compatible('keras-preprocessing') }}
    - {{ pin_compatible('six') }}
    - {{ pin_compatible('protobuf') }}
    - {{ pin_compatible('google-pasta') }}
    - {{ pin_compatible('termcolor') }}
    - {{ pin_compatible('grpcio') }}
    - {{ pin_compatible('mock') }}               # [py2k]
    - {{ pin_compatible('backports.weakref') }}  # [py2k]
    - {{ pin_compatible('enum34') }}             # [py2k]
    - future                                     # [py2k]
    - wrapt >=1.11

test:
  imports:
    - tensorflow
  commands:
    # estimator_ckpt_converter requires tensorflow-estimator
    #- estimator_ckpt_converter --help
    - saved_model_cli --help
    - tf_upgrade_v2 --help
    - tflite_convert --help     # [not win]
    - toco --help               # [not win]
    - toco_from_protos --help   # [not win]

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  license_family: Apache
  summary: TensorFlow is a machine learning library, base package contains only tensorflow.
  description: |
    TensorFlow provides multiple APIs.The lowest level API, TensorFlow Core
    provides you with complete programming control.
    Base package contains only tensorflow, not tensorflow-tensorboard.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src

extra:
  tflow_variant: {{ tflow_variant }}
