# The MKL variant is removed because Clang still has trouble building with OpenMP,
# which is enabled when MKL is turned on.
tflow_variant:
  - eigen
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.15"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.15"                # [osx and x86_64]
CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.15.sdk   # [osx and x86_64]