{% set version = "2.9.1" %}
{% set major_minor = version.rsplit('.', 1)[0] %}

# This is the recipe for the "mkl" and "eigen" variants of tensorflow-base, but the MKL variant
# has been disabled because OpenMP doesn't play well with clang.
package:
  name: tensorflow-base
  version: {{ version }}

source:
  fn: tensorflow-{{ version }}.tar.gz
  url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz
  sha256: 6eaf86ead73e23988fe192da1db68f4d3828bcdd0f3a9dc195935e339c95dbdc
  patches:
    - 0101-include-c-and-cc-headers.patch
    - 0107-do-not-hardcode-ca-cert-location.patch
    - 0108-fix-absl-stuff.patch

build:
  number: 0
  skip: True  # [not x86_64 or not osx]
  string: {{ tflow_variant }}_py{{ CONDA_PY }}h{{PKG_HASH}}_{{ PKG_BUILDNUM }}
  entry_points:
    - toco_from_protos = tensorflow.lite.toco.python.toco_from_protos:main
    - tflite_convert = tensorflow.lite.python.tflite_convert:main
    - toco = tensorflow.lite.python.tflite_convert:main
    - saved_model_cli = tensorflow.python.tools.saved_model_cli:main
    # The tensorboard package adds this entry point.
    # - tensorboard = tensorboard.main:run_main
    - tf_upgrade_v2 = tensorflow.tools.compatibility.tf_upgrade_v2_main:main
    - estimator_ckpt_converter = tensorflow_estimator.python.estimator.tools.checkpoint_converter:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
    - patch
    # required here for all OS's
    - bazel >=5.2.0
    - aws-sdk-cpp
    # - abseil-cpp
    - llvm-openmp 
    - llvm-tools
    - libtool
    - zlib
    - python
    - mkl >=2021         # [tflow_variant == 'mkl']
    - cython
    - sqlite
    - grpc-cpp
    - llvm-openmp
    - wheel
  host:
    # conda build requirements for .sh scripts on win
    - python
    - pip
    - setuptools
    - wheel
    - libcurl
    - unzip
    - zip
    - nsync
    # requirements specified by the package itself
    - astor >=0.7.1
    - cython
    - dill >=0.3.1.1
    - giflib
    - grpc-cpp
    - flatbuffers 1.12.*
    - icu
    - jpeg
    - libpng
    - libprotobuf
    - openssl
    - pybind11
    - sqlite
    - snappy
    - zlib
    - abseil-cpp
    - absl-py 0.11
    - astunparse 1.6.3
    - python-flatbuffers 1.12.*
    - gast 0.4.0
    - google-pasta 0.2
    - grpcio
    - h5py >=3.1.0
    - keras-preprocessing >=1.1.2
    - numpy 1.20  # [py<=39]
    - numpy 1.21  # [py>39]
    - opt_einsum 3.3.0.*
    # build only requirement, doesn't need a run dep below
    - protobuf >=3.9.2
    # build only requirement, doesn't need a run dep below
    - scipy 1.7.3
    - six >=1.15.0
    - typing_extensions >=3.7.4
    # build only requirement, doesn't need a run dep below
    - swig
    - termcolor >=1.1.0
    - wrapt >=1.11.2
    # has run_exports, doesn't need a run dep below
    - sqlite
    - llvm-openmp
    - snappy
    - packaging
  run:
    - python
    - absl-py >=0.10.0
    - astunparse >=1.6.3
    - python-flatbuffers 1.12.*
    - google-pasta >=0.2
    - h5py >=3.1.0
    - keras {{ major_minor }}.*
    - numpy >=1.20
    - opt_einsum 3.3.0.*
    - protobuf >=3.9.2
    - six >=1.15.0
    - termcolor >=1.1.0
    - typing_extensions >=3.7.4
    - wheel >=0.35,<0.36
    - wrapt >=1.11.2
    - grpcio
    - packaging
    # upstream wants exact pin for gast
    - gast ==0.4.0
    - scipy >=1.7.3,<2
    - flatbuffers
    - llvm-openmp
    - tensorboard {{ major_minor }}.*
    - tensorflow-estimator {{ major_minor }}.*
test:
  imports:
    - tensorflow
  commands:
    # estimator_ckpt_converter requires tensorflow-estimator
    #- estimator_ckpt_converter --help
    - saved_model_cli --help
    - tf_upgrade_v2 --help
    - tflite_convert --help
    - toco --help
    - toco_from_protos --help

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  license_family: Apache
  summary: TensorFlow is a machine learning library, base package contains only tensorflow.
  description: |
    TensorFlow provides multiple APIs.The lowest level API, TensorFlow Core
    provides you with complete programming control.
    Base package contains only tensorflow, not tensorflow-tensorboard.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src

extra:
  tflow_variant: {{ tflow_variant }}
