{% set version = "2.0.0" %}

package:
  name: tensorboard
  version: {{ version }}

source:
  fn: tensorboard-{{ version }}.tar.gz
  url: https://github.com/tensorflow/tensorboard/archive/{{ version }}.tar.gz
  sha256: b535414d818350f9d879d04bc3d1ed0026b09e55ffea5131456cd8758806287a

build:
  number: 0
  # we build it noarch on win for py3.x, and we skip win with py27.
  skip: True  # [win]
  skip: True  # [not x86_64]
  noarch: python  # [py3k]
  # Make sure there is no tensorboard entry point in the tensorflow-{gpu-,}base
  # packages as it conflicts with a file in this package.
  entry_points:
    - tensorboard = tensorboard.main:run_main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - bazel >=0.26.1
    - python
    - pip
  run:
    - python        # [py2k]
    - python >=3.5  # [py3k]
    - absl-py >={{absl_py}}
    - grpcio >={{grpcio}}
    - markdown >={{markdown}}
    - numpy >={{numpy_devel}}
    - protobuf >={{protobuf}}
    - six >={{six}}
    - werkzeug >={{werkzeug}}
    - futures >=3.1.1  # [py27]

test:
  requires:
    - tensorflow-base {{version}}
    - tensorflow-estimator {{version}}
  imports:
    - tensorboard
  commands:
    - tensorboard --help

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  license_family: Apache
  summary: TensorBoard lets you watch Tensors Flow
  dev_url: https://github.com/tensorflow/tensorboard
