{% set name = "tensorboard" %}
{% set version = "2.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/t/tensorboard/tensorboard-{{ version }}-py3-none-any.whl
  sha256: fb9222c1750e2fa35ef170d998a1e229f626eeced3004494a8849c88c15d8c1c

build:
  number: 0
  skip: True  # [py<36]
  script:
    - python -m pip install --no-deps --ignore-installed ./tensorboard-{{ version }}-py3-none-any.whl
  entry_points:
    - tensorboard = tensorboard.main:run_main

requirements:
  host:
    - python
    - pip
  run:
    - absl-py >=0.4
    - google-auth-oauthlib >=0.4.1,<0.5
    - grpcio >=1.24.3
    - markdown >=2.6.8
    - numpy >=1.12.0
    - protobuf >=3.6.0
    - python
    - requests >=2.21.0,<3
    - setuptools >=41.0.0
    - tensorboard-data-server >=0.6.0,<0.7.0
    - tensorboard-plugin-wit >=1.6.0
    - werkzeug >=1.0.1
    - wheel >=0.26

test:
  imports:
    - tensorboard
  commands:
    - tensorboard -h

about:
  home: https://www.tensorflow.org/tensorboard
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: TensorFlow's Visualization Toolkit
  dev_url: https://github.com/tensorflow/tensorboard
  doc_url: https://www.tensorflow.org/tensorboard/get_started

extra:
  recipe-maintainers:
    - sdvillal
    - gilbertfrancois
    - farhantejani
    - mdraw
    - jschueller
