{% set name = "tensorboard" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/t/tensorboard/tensorboard-{{ version }}-py3-none-any.whl
  sha256: 65a338e4424e9079f2604923bdbe301792adce2ace1be68da6b3ddf005170def

build:
  number: 0
  skip: True  # [py<37]
  script:
    - python -m pip install --no-deps --ignore-installed ./tensorboard-{{ version }}-py3-none-any.whl
  entry_points:
    - tensorboard = tensorboard.main:run_main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - wheel >=0.26
    - numpy >=1.12.0
    - protobuf >=3.6.0
    - werkzeug >=0.11.15
    - markdown >=2.6.8
    - absl-py >=0.4
    - grpcio >=1.24.3
    - google-auth-oauthlib ==0.4.1
    - tensorboard-plugin-wit >=1.6.0
    - tensorboard-data-server >=0.6.0,<0.7.0

test:
  imports:
    - tensorboard
  commands:
    - tensorboard -h

about:
  home: https://www.tensorflow.org/tensorboard
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: TensorFlow's Visualization Toolkit
  dev_url: https://github.com/tensorflow/tensorboard
  doc_url: https://www.tensorflow.org/tensorboard/get_started

extra:
  recipe-maintainers:
    - sdvillal
    - gilbertfrancois
    - farhantejani
    - mdraw
    - jschueller
