{% set version = "1.14.0" %}

package:
  name: tensorboard
  version: {{ version }}

source:
  fn: tensorboard-{{ version }}.tar.gz                                         # [unix]
  url: https://github.com/tensorflow/tensorboard/archive/{{ version }}.tar.gz  # [unix]
  sha256: bba9993f1b8fb0617ab537241bb5705bed370b04b96d5e96e31263fe273505be     # [unix]

  # Rename this to dummy since we don't want CB to extract it
  fn: tensorboard-{{ version }}-py3-none-any.whl.dummy                                        # [win]
  url: https://pypi.io/packages/py3/t/tensorboard/tensorboard-{{ version }}-py3-none-any.whl  # [win]
  sha256: bba9993f1b8fb0617ab537241bb5705bed370b04b96d5e96e31263fe273505be                    # [win]

build:
  number: 0
  skip: True  # [not x86_64]
  skip: True  # [win and vc<14]
  # Make sure there is no tensorboard entry point in the tensorflow-{gpu-,}base
  # packages as it conflicts with a file in this package.
  entry_points:
    - tensorboard = tensorboard.main:run_main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # Not using bazel on Windows due to issue with long paths
    # The package contents are not OS specific anyway
    - bazel 0.22.0
    - python
    - pip
  run:
    - python
    - absl-py >=0.4
    - grpcio >=1.6.3
    - markdown >=2.6.8
    - numpy >=1.12.0
    - protobuf >=3.6.0
    - six >=1.10.0
    - werkzeug >=0.11.15
    - futures >=3.1.1  # [py27]

test:
  requires:
    - tensorflow-base >=1.14.0,<1.15.0a0
    - tensorflow-estimator 1.14.0
  imports:
    - tensorboard
  commands:
    - tensorboard --help

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  license_family: Apache
  summary: TensorBoard lets you watch Tensors Flow
  dev_url: https://github.com/tensorflow/tensorboard
