# NOTE: bazel refuses to use our python in this build, despite many hacky attempts you can see in build.sh
#    To make this recipe build, /usr/bin/python must exist.  I symlinked /usr/bin/python3 to /usr/bin/python
#    and that was sufficient.
{% set version = "2.4.0" %}
{% set tf_version = "2.4.1" %}

package:
  name: tensorboard
  version: {{ version }}

source:
  fn: tensorboard-{{ version }}.tar.gz
  url: https://github.com/tensorflow/tensorboard/archive/{{ version }}.tar.gz
  sha256: 28a30794c1c797357b2086477394b59afa0b18ca48592ca3c0627f7f10536373

# tensorboard is built as a noarch packages on a Linux system
# During the build, an executable is downloaded that requires a newer
# version of libstdc++ than that provided by CentOS 6,  Ubuntu 16.04 works.
build:
  number: 0
  noarch: python
  # Make sure there is no tensorboard entry point in the tensorflow-{gpu-,}base
  # packages as it conflicts with a file in this package.
  entry_points:
    - tensorboard = tensorboard.main:run_main
  # Although compilers are needed for the build, the output is pure python,
  # javascript and html. Therefore the run_exports can be ignored.
  ignore_run_exports:
    - libgcc-ng
    - libstdcxx-ng
    - libcxx

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - bazel >=0.29.1
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - absl-py >={{absl_py}}
    - grpcio >=1.24.3
    - google-auth >=1.6.3,<2
    - google-auth-oauthlib >=0.4.1,<0.5
    - markdown >={{markdown}}
    - numpy >={{numpy}}
    - protobuf >={{protobuf}}
    - requests >=2.21.0,<3
    - setuptools >={{setuptools}}
    - six >={{six}}
    - tensorboard-plugin-wit >=1.6.0
    - werkzeug >=0.11.15
    - markdown >=2.6.8
    - wheel >=0.26

test:
  requires:
    - tensorflow-base {{tf_version}}
    - tensorflow-estimator {{tf_version}}
  imports:
    - tensorboard
  commands:
    - tensorboard --help

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  license_family: Apache
  summary: TensorBoard lets you watch Tensors Flow
  dev_url: https://github.com/tensorflow/tensorboard
