{% set name = "tensorboard" %}
{% set version = "2.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/t/tensorboard/tensorboard-{{ version }}-py3-none-any.whl
  sha256: 3cbdc32448d7a28dc1bf0b1754760c08b8e0e2e37c451027ebd5ff4896613012

build:
  number: 0
  skip: True  # [py<36]
  script:
    - python -m pip install --no-deps --ignore-installed ./tensorboard-{{ version }}-py3-none-any.whl
  entry_points:
    - tensorboard = tensorboard.main:run_main

requirements:
  host:
    - python
    - pip
  run:
    - absl-py >=0.4
    - google-auth >=1.6.3,<3
    - google-auth-oauthlib >=0.4.1,<1.15
    - grpcio >=1.48.2
    - markdown >=2.6.8
    - numpy >=1.12.0
    - protobuf >=3.19.6
    - python
    - requests >=2.21.0,<3
    - setuptools >=41.0.0
    - tensorboard-data-server >=0.7.0,<0.8.0
    - tensorboard-plugin-wit >=1.6.0
    - werkzeug >=1.0.1
    - wheel >=0.26

test:
  imports:
    - tensorboard
  commands:
    - tensorboard -h

about:
  home: https://www.tensorflow.org/tensorboard
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: TensorFlow's Visualization Toolkit
  dev_url: https://github.com/tensorflow/tensorboard
  doc_url: https://www.tensorflow.org/tensorboard/get_started

extra:
  recipe-maintainers:
    - sdvillal
    - gilbertfrancois
    - farhantejani
    - mdraw
    - jschueller
