{% set version = "0.1.7" %}

package:
  name: google-pasta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/google-pasta/google-pasta-{{ version }}.tar.gz
  sha256: 79d1ce28b381d68e98ef7707d19909adb58912f8dae8734402454424fc76b8fe

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six

test:
  imports:
    - pasta
    - pasta.augment
    - pasta.base

about:
  home: https://github.com/google/pasta
  home: The package home page
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: pasta is an AST-based Python refactoring library

extra:
  recipe-maintainers:
    - jjhelmus
